import { IntegrationDef } from "./types";

// Integration catalog - modeled after OpenClaw
export const INTEGRATION_CATALOG: IntegrationDef[] = [
  // AI Models
  {
    id: "openai",
    name: "OpenAI",
    description: "GPT-4, GPT-3.5, DALL-E, and Whisper APIs",
    category: "ai_models",
    icon: "openai",
    specUrl: "https://app.stainless.com/api/spec/documented/openai/openapi.documented.yml",
    authType: "bearer",
    docsUrl: "https://platform.openai.com/docs",
    tags: ["llm", "chat", "images", "audio"],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    description: "Claude AI models for chat and analysis",
    category: "ai_models",
    icon: "anthropic",
    authType: "api_key",
    authHeader: "x-api-key",
    docsUrl: "https://docs.anthropic.com",
    tags: ["llm", "chat", "analysis"],
  },
  {
    id: "google-ai",
    name: "Google AI",
    description: "Gemini models for multimodal AI",
    category: "ai_models",
    icon: "google",
    authType: "api_key",
    docsUrl: "https://ai.google.dev/docs",
    tags: ["llm", "multimodal"],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    description: "Mistral and Mixtral language models",
    category: "ai_models",
    icon: "mistral",
    authType: "bearer",
    docsUrl: "https://docs.mistral.ai",
    tags: ["llm", "chat"],
  },
  {
    id: "groq",
    name: "Groq",
    description: "Ultra-fast LLM inference",
    category: "ai_models",
    icon: "groq",
    authType: "bearer",
    docsUrl: "https://console.groq.com/docs",
    tags: ["llm", "fast"],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    description: "Access thousands of ML models",
    category: "ai_models",
    icon: "huggingface",
    authType: "bearer",
    docsUrl: "https://huggingface.co/docs",
    tags: ["llm", "models", "inference"],
  },
  {
    id: "replicate",
    name: "Replicate",
    description: "Run open-source ML models in the cloud",
    category: "ai_models",
    icon: "replicate",
    authType: "bearer",
    docsUrl: "https://replicate.com/docs",
    tags: ["ml", "images", "video"],
  },
  {
    id: "cohere",
    name: "Cohere",
    description: "Enterprise AI for text understanding",
    category: "ai_models",
    icon: "cohere",
    authType: "bearer",
    docsUrl: "https://docs.cohere.com",
    tags: ["llm", "embeddings", "enterprise"],
  },

  // Chat & Messaging
  {
    id: "slack",
    name: "Slack",
    description: "Team messaging and collaboration",
    category: "chat",
    icon: "slack",
    authType: "bearer",
    docsUrl: "https://api.slack.com/docs",
    tags: ["messaging", "teams", "bots"],
  },
  {
    id: "discord",
    name: "Discord",
    description: "Community and gaming chat platform",
    category: "chat",
    icon: "discord",
    authType: "bearer",
    docsUrl: "https://discord.com/developers/docs",
    tags: ["messaging", "communities", "bots"],
  },
  {
    id: "telegram",
    name: "Telegram",
    description: "Secure messaging with bot API",
    category: "chat",
    icon: "telegram",
    authType: "bearer",
    docsUrl: "https://core.telegram.org/bots/api",
    tags: ["messaging", "bots"],
  },
  {
    id: "twilio",
    name: "Twilio",
    description: "SMS, voice, and messaging APIs",
    category: "chat",
    icon: "twilio",
    authType: "basic",
    docsUrl: "https://www.twilio.com/docs",
    tags: ["sms", "voice", "messaging"],
  },

  // Productivity
  {
    id: "github",
    name: "GitHub",
    description: "Code hosting and collaboration",
    category: "productivity",
    icon: "github",
    specUrl: "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json",
    authType: "bearer",
    docsUrl: "https://docs.github.com/en/rest",
    tags: ["git", "code", "issues", "prs"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "DevOps platform for code and CI/CD",
    category: "productivity",
    icon: "gitlab",
    authType: "bearer",
    docsUrl: "https://docs.gitlab.com/ee/api",
    tags: ["git", "code", "cicd"],
  },
  {
    id: "notion",
    name: "Notion",
    description: "All-in-one workspace for notes and docs",
    category: "productivity",
    icon: "notion",
    authType: "bearer",
    docsUrl: "https://developers.notion.com",
    tags: ["notes", "docs", "databases"],
  },
  {
    id: "linear",
    name: "Linear",
    description: "Issue tracking for modern teams",
    category: "productivity",
    icon: "linear",
    authType: "bearer",
    docsUrl: "https://developers.linear.app",
    tags: ["issues", "projects", "teams"],
  },
  {
    id: "jira",
    name: "Jira",
    description: "Project and issue tracking",
    category: "productivity",
    icon: "jira",
    authType: "basic",
    docsUrl: "https://developer.atlassian.com/cloud/jira",
    tags: ["issues", "projects", "agile"],
  },
  {
    id: "trello",
    name: "Trello",
    description: "Visual project management boards",
    category: "productivity",
    icon: "trello",
    authType: "api_key",
    docsUrl: "https://developer.atlassian.com/cloud/trello",
    tags: ["boards", "tasks", "kanban"],
  },
  {
    id: "asana",
    name: "Asana",
    description: "Work management platform",
    category: "productivity",
    icon: "asana",
    authType: "bearer",
    docsUrl: "https://developers.asana.com",
    tags: ["tasks", "projects", "teams"],
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Flexible database and spreadsheet hybrid",
    category: "productivity",
    icon: "airtable",
    authType: "bearer",
    docsUrl: "https://airtable.com/developers",
    tags: ["databases", "spreadsheets"],
  },

  // Smart Home
  {
    id: "home-assistant",
    name: "Home Assistant",
    description: "Open-source home automation hub",
    category: "smart_home",
    icon: "home-assistant",
    authType: "bearer",
    docsUrl: "https://developers.home-assistant.io",
    tags: ["automation", "iot", "smart-home"],
  },
  {
    id: "philips-hue",
    name: "Philips Hue",
    description: "Smart lighting control",
    category: "smart_home",
    icon: "philips-hue",
    authType: "api_key",
    docsUrl: "https://developers.meethue.com",
    tags: ["lighting", "smart-home"],
  },

  // Tools & Automation
  {
    id: "stripe",
    name: "Stripe",
    description: "Payment processing and billing",
    category: "tools",
    icon: "stripe",
    specUrl: "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json",
    authType: "bearer",
    docsUrl: "https://stripe.com/docs/api",
    tags: ["payments", "billing", "subscriptions"],
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    description: "Email delivery and marketing",
    category: "tools",
    icon: "sendgrid",
    authType: "bearer",
    docsUrl: "https://docs.sendgrid.com",
    tags: ["email", "marketing"],
  },
  {
    id: "mailgun",
    name: "Mailgun",
    description: "Transactional email API",
    category: "tools",
    icon: "mailgun",
    authType: "basic",
    docsUrl: "https://documentation.mailgun.com",
    tags: ["email", "transactional"],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    description: "CDN, DNS, and edge computing",
    category: "tools",
    icon: "cloudflare",
    authType: "bearer",
    docsUrl: "https://developers.cloudflare.com",
    tags: ["cdn", "dns", "security"],
  },
  {
    id: "vercel",
    name: "Vercel",
    description: "Frontend deployment platform",
    category: "tools",
    icon: "vercel",
    authType: "bearer",
    docsUrl: "https://vercel.com/docs/rest-api",
    tags: ["deployment", "hosting", "serverless"],
  },
  {
    id: "aws",
    name: "AWS",
    description: "Amazon Web Services cloud platform",
    category: "tools",
    icon: "aws",
    authType: "api_key",
    docsUrl: "https://docs.aws.amazon.com",
    tags: ["cloud", "infrastructure"],
  },

  // Media & Creative
  {
    id: "spotify",
    name: "Spotify",
    description: "Music streaming and playback control",
    category: "media",
    icon: "spotify",
    authType: "oauth2",
    docsUrl: "https://developer.spotify.com/documentation",
    tags: ["music", "streaming", "playlists"],
  },
  {
    id: "youtube",
    name: "YouTube",
    description: "Video platform and streaming",
    category: "media",
    icon: "youtube",
    authType: "api_key",
    docsUrl: "https://developers.google.com/youtube",
    tags: ["video", "streaming"],
  },
  {
    id: "unsplash",
    name: "Unsplash",
    description: "High-quality stock photos",
    category: "media",
    icon: "unsplash",
    authType: "bearer",
    docsUrl: "https://unsplash.com/documentation",
    tags: ["images", "photos", "stock"],
  },

  // Social
  {
    id: "twitter",
    name: "X (Twitter)",
    description: "Social media posting and reading",
    category: "social",
    icon: "twitter",
    authType: "oauth2",
    docsUrl: "https://developer.twitter.com/en/docs",
    tags: ["social", "posts", "timeline"],
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Professional networking platform",
    category: "social",
    icon: "linkedin",
    authType: "oauth2",
    docsUrl: "https://learn.microsoft.com/en-us/linkedin",
    tags: ["social", "professional", "jobs"],
  },
];

// Get integrations by category
export function getIntegrationsByCategory(category: string): IntegrationDef[] {
  return INTEGRATION_CATALOG.filter((i) => i.category === category);
}

// Search integrations
export function searchIntegrations(query: string): IntegrationDef[] {
  const q = query.toLowerCase();
  return INTEGRATION_CATALOG.filter(
    (i) =>
      i.name.toLowerCase().includes(q) ||
      i.description.toLowerCase().includes(q) ||
      i.tags?.some((t) => t.toLowerCase().includes(q))
  );
}

// Get integration by ID
export function getIntegrationById(id: string): IntegrationDef | undefined {
  return INTEGRATION_CATALOG.find((i) => i.id === id);
}
